source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DownloadButton_Example' do
  pod "DownloadButton", :path => "../"
end

target 'DownloadButton_Tests' do
  pod "DownloadButton", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
